public enum LHD_EGameTipType
{
	NoneTip = -1,
	Net_ConnectionError,
	LoseTheServer,
	UserIDFrozen,
	CoinOverFlow,
	ApplyForExpCoin_Success,
	SelectTable_CreditBelowRistrict,
	SelectTable_SendExpCoin,
	SelectSeat_NotEmpty,
	RoomEmpty,
	IsExitGame,
	TableParameterModified,
	TableDeleted_Game,
	LongTimeNoOperate,
	ServerUpdate,
	Game_UserIdFrozen,
	UserIdDeleted,
	UserIdRepeative,
	UserPwdChanged,
	UserIdPwdNotMatch,
	GivingCoin,
	IsExitApplication,
	PoorNetSignal,
	OutGame,
	OutGame2
}
