public enum XLDT_BET_PRIZE_TYPE
{
	KNOWN_PRIZE_COLOR_RED,
	KNOWN_PRIZE_COLOR_BLACK,
	KNOWN_PRIZE_POKER_SPADE,
	KNOWN_PRIZE_POKER_HEART,
	KNOWN_PRIZE_POKER_CLUB,
	KNOWN_PRIZE_POKER_DIAMOND,
	KNOWN_PRIZE_PORKER_JOKER,
	PRIZE_NORMAL
}
