namespace GameCommon
{
	public enum STMF_RENDER_LAYER
	{
		RENDER_LAYER_FISH = 640,
		RENDER_LAYER_BACKGROUND = -1,
		RENDER_FISHNET = 641,
		RENDER_LAYER_ROLLBG = 642,
		RENDER_DEAD_FISH = 643,
		RENDER_EFFECT = 644,
		RENDER_NUMBER = 645
	}
}
