namespace GameCommon
{
	public enum STMF_BULLET_TYPE
	{
		BULLET_TYP_NORMAL1,
		BULLET_TYP_NORMAL2,
		BULLET_TYP_NORMAL3,
		BULLET_TYP_NORMAL4,
		BULLET_TYP_NORMAL_LIZI,
		BULLET_TYP_SUPER1,
		BULLET_TYP_SUPER2,
		BULLET_TYP_SUPER3,
		BULLET_TYP_SUPER4,
		BULLET_TYP_SUPER_LIZI
	}
}
